#!/bin/bash

# receive the 10 numbers from the Script of Task 1 (adjust_task_1)
declare -a output_array="($(sh adjust_task_1))"

# print the output
echo -e "output: ${output_array[*]}\n"

# get length of output_array
len=${#output_array[@]}

# variable to know which index of the array I am in
i=0

# if all the conditions are met, the value of this variable keeps in "true"
successful=true

# loop until the index is equal to the array length
while [ $i -lt $len ]
do

 # read the value of the array corresponding to the index
 value="${output_array[i]}"

 # number_suffix is a variable just to print the ordinal number in a more correct way
 if [ "$((i+1))" -eq "1" ]
 then
  number_suffix="st"

 elif [ "$((i+1))" -eq "2" ]
 then
  number_suffix="nd"

 elif [ "$((i+1))" -eq "3" ]
 then
  number_suffix="rd"

 else
  number_suffix="th"

 fi

 # print the number
 echo -e "The $((i+1))$number_suffix number is $value"

 # check if value already exists in the temporal array
 if [[ " ${temp_array[@]} " =~ " ${value} " ]]
 then
   echo -e "This number is repeated"
   successful=false

 fi

 # store the value in the temporal array
 temp_array[i]=$value

 # check if the number is between 1 and 10
 if [ "$value" -ge "1" ] && [ "$value" -le "10" ]
 then
  echo -e "The value is within the range\n"

 else
  echo -e "The value is not within the range\n"
  successful=false

 fi

 # following index
 ((i=i+1))

done

# the task is only successful if "successful" boolean variable is equal to "true"
if [ "$successful" = true ]
then
 echo -e "All the values are within the range and none of the numbers is repeated. Therefore, the task is successful\n"

else
 echo -e "The task is not successful\n"

fi
